force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Bus_Status__c.field-meta.xml
<CustomField>
    <fullName>Bus_Status__c</fullName>
    <label>Bus Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Limited Seats</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Passenger_Count__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Count__c</fullName>
    <label>Passenger Count</label>
    <summaryForeignKey>Passenger__c.Bus__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BusStatusUpdateBatch_TEST.cls
@isTest
public class BusStatusUpdateBatch_TEST 
{
    @isTest
    static void BusStatusUpdateBatch_TEST() 
    {
        List<Bus__c> busesList = new List<Bus__c>();
        List<Passenger__c> passengersList = new List<Passenger__c>();

        for (Integer i = 0; i < 200; i++) 
        {
            busesList.add(new Bus__c(
                Name = 'Bus ' + i
            ));
        }

        insert busesList;

        for (Bus__c bus : busesList) 
        {
            Integer passengerCount = Math.mod(Crypto.getRandomInteger(), 26); 
            if (passengerCount < 0)
            {
                passengerCount *= -1;
            }

            for (Integer j = 0; j < passengerCount; j++) 
            {
                passengersList.add(new Passenger__c(
                    Name = 'P' + bus.Name.split(' ')[1] + '-' + j,
                    Bus__c = bus.Id
                ));
            }
        }

        insert passengersList;

        List<Id> busIdsList = new List<Id>();
        for (Bus__c bus : busesList) 
        {
            busIdsList.add(bus.Id);
        }

        Test.startTest();
            BusStatusUpdateBatch batch = new BusStatusUpdateBatch(busIdsList);
            Database.executeBatch(batch, 200);
        Test.stopTest();

        busesList = [SELECT Name, Bus_Status__c, Passenger_Count__c FROM Bus__c ORDER BY Name];

        for (Bus__c bus : busesList) 
        {
            Integer count = bus.Passenger_Count__c != null ? Integer.valueOf(bus.Passenger_Count__c) : 0;

            if (count > 20) 
            {
                Assert.areEqual(null, bus.Bus_Status__c, 'Bus with >20 passengers should not be updated: ' + bus.Name);
            } 
            else if (count == 20) 
            {
                Assert.areEqual('Full', bus.Bus_Status__c, 'Bus with 20 passengers should be Full: ' + bus.Name);
            } 
            else if (count > 10) 
            {
                Assert.areEqual('Limited Seats', bus.Bus_Status__c, 'Bus with 11-19 passengers should be Limited Seats: ' + bus.Name);
            } 
            else 
            {
                Assert.areEqual('Available', bus.Bus_Status__c, 'Bus with <10 passengers should be Available: ' + bus.Name);
            }
        }
    }

    @isTest
    static void BusStatusUpdateBatch_EmptyList_TEST()
    {
        List<Id> busIdsList = new List<Id>();

        Test.startTest();
            BusStatusUpdateBatch batch = new BusStatusUpdateBatch(busIdsList);
            Database.executeBatch(batch, 200);
        Test.stopTest();
    }
}